--
-- PostgreSQL database dump
--

\restrict D0j0grVEmedvbrUY3epnhHutEi1ciFtAlzpQ8NXgac3Yg8YXaT6LyXADxQhPQFw

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: suvidha_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO suvidha_user;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: suvidha_user
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_apiaccesslog; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.audit_apiaccesslog (
    id bigint NOT NULL,
    endpoint character varying(200) NOT NULL,
    method character varying(10) NOT NULL,
    ip_address inet,
    response_status integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.audit_apiaccesslog OWNER TO suvidha_user;

--
-- Name: audit_apiaccesslog_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.audit_apiaccesslog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_apiaccesslog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_auditlog; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.audit_auditlog (
    id bigint NOT NULL,
    action_type character varying(20) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id character varying(50),
    ip_address inet,
    details jsonb NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.audit_auditlog OWNER TO suvidha_user;

--
-- Name: audit_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.audit_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO suvidha_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO suvidha_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO suvidha_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_phoneotp; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.authentication_phoneotp (
    id bigint NOT NULL,
    phone character varying(15) NOT NULL,
    otp character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_verified boolean NOT NULL
);


ALTER TABLE public.authentication_phoneotp OWNER TO suvidha_user;

--
-- Name: authentication_phoneotp_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.authentication_phoneotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_phoneotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_bill; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.billing_bill (
    bill_id character varying(50) NOT NULL,
    account_type character varying(20) NOT NULL,
    consumer_number character varying(50) NOT NULL,
    bill_date date NOT NULL,
    due_date date NOT NULL,
    amount numeric(12,2) NOT NULL,
    arrears numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL
);


ALTER TABLE public.billing_bill OWNER TO suvidha_user;

--
-- Name: billing_billlineitem; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.billing_billlineitem (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    amount numeric(10,2) NOT NULL,
    quantity numeric(6,2) NOT NULL,
    bill_id character varying(50) NOT NULL
);


ALTER TABLE public.billing_billlineitem OWNER TO suvidha_user;

--
-- Name: billing_billlineitem_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.billing_billlineitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_billlineitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_electricityaccount; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.billing_electricityaccount (
    id bigint NOT NULL,
    consumer_number character varying(50) NOT NULL,
    account_holder character varying(100) NOT NULL,
    address text NOT NULL,
    connection_type character varying(50) NOT NULL,
    meter_number character varying(50) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.billing_electricityaccount OWNER TO suvidha_user;

--
-- Name: billing_electricityaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.billing_electricityaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_electricityaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_gasaccount; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.billing_gasaccount (
    id bigint NOT NULL,
    consumer_number character varying(50) NOT NULL,
    account_holder character varying(100) NOT NULL,
    address text NOT NULL,
    connection_type character varying(50) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.billing_gasaccount OWNER TO suvidha_user;

--
-- Name: billing_gasaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.billing_gasaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_gasaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_wateraccount; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.billing_wateraccount (
    id bigint NOT NULL,
    consumer_number character varying(50) NOT NULL,
    account_holder character varying(100) NOT NULL,
    address text NOT NULL,
    connection_type character varying(50) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.billing_wateraccount OWNER TO suvidha_user;

--
-- Name: billing_wateraccount_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.billing_wateraccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_wateraccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_faqcontent; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.content_faqcontent (
    id bigint NOT NULL,
    category character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    question text NOT NULL,
    answer text NOT NULL
);


ALTER TABLE public.content_faqcontent OWNER TO suvidha_user;

--
-- Name: content_faqcontent_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.content_faqcontent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_faqcontent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_servicecontent; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.content_servicecontent (
    id bigint NOT NULL,
    service_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.content_servicecontent OWNER TO suvidha_user;

--
-- Name: content_servicecontent_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.content_servicecontent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_servicecontent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO suvidha_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO suvidha_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO suvidha_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO suvidha_user;

--
-- Name: grievances_complaint; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.grievances_complaint (
    id bigint NOT NULL,
    complaint_id character varying(50) NOT NULL,
    service_type character varying(50) NOT NULL,
    category character varying(50) NOT NULL,
    description text NOT NULL,
    priority character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.grievances_complaint OWNER TO suvidha_user;

--
-- Name: grievances_complaint_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.grievances_complaint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grievances_complaint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grievances_complaintattachment; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.grievances_complaintattachment (
    id bigint NOT NULL,
    file_path character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    complaint_id bigint NOT NULL
);


ALTER TABLE public.grievances_complaintattachment OWNER TO suvidha_user;

--
-- Name: grievances_complaintattachment_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.grievances_complaintattachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grievances_complaintattachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grievances_complaintupdate; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.grievances_complaintupdate (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    remarks text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    complaint_id bigint NOT NULL,
    updated_by_id bigint
);


ALTER TABLE public.grievances_complaintupdate OWNER TO suvidha_user;

--
-- Name: grievances_complaintupdate_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.grievances_complaintupdate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grievances_complaintupdate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    notification_type character varying(50) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.notifications_notification OWNER TO suvidha_user;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_systemalert; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.notifications_systemalert (
    id bigint NOT NULL,
    alert_type character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    severity character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.notifications_systemalert OWNER TO suvidha_user;

--
-- Name: notifications_systemalert_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.notifications_systemalert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_systemalert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    payment_id character varying(50) NOT NULL,
    amount numeric(12,2) NOT NULL,
    payment_method character varying(50) NOT NULL,
    transaction_id character varying(100),
    gateway_reference character varying(100),
    status character varying(20) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    bill_id character varying(50) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.payments_payment OWNER TO suvidha_user;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_paymentreceipt; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.payments_paymentreceipt (
    id bigint NOT NULL,
    receipt_number character varying(50) NOT NULL,
    receipt_data jsonb NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    payment_id bigint NOT NULL
);


ALTER TABLE public.payments_paymentreceipt OWNER TO suvidha_user;

--
-- Name: payments_paymentreceipt_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.payments_paymentreceipt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_paymentreceipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rest_framework_api_key_apikey; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.rest_framework_api_key_apikey (
    id character varying(150) NOT NULL,
    created timestamp with time zone NOT NULL,
    name character varying(50) NOT NULL,
    revoked boolean NOT NULL,
    expiry_date timestamp with time zone,
    hashed_key character varying(150) NOT NULL,
    prefix character varying(8) NOT NULL
);


ALTER TABLE public.rest_framework_api_key_apikey OWNER TO suvidha_user;

--
-- Name: service_requests_requestdocument; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.service_requests_requestdocument (
    id bigint NOT NULL,
    document_type character varying(50) NOT NULL,
    file_path character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    service_request_id bigint NOT NULL
);


ALTER TABLE public.service_requests_requestdocument OWNER TO suvidha_user;

--
-- Name: service_requests_requestdocument_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.service_requests_requestdocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_requests_requestdocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_requests_servicerequest; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.service_requests_servicerequest (
    id bigint NOT NULL,
    request_id character varying(50) NOT NULL,
    service_type character varying(50) NOT NULL,
    request_type character varying(50) NOT NULL,
    details jsonb NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.service_requests_servicerequest OWNER TO suvidha_user;

--
-- Name: service_requests_servicerequest_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.service_requests_servicerequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_requests_servicerequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO suvidha_user;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255)
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO suvidha_user;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_management_customuser; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.user_management_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone character varying(15) NOT NULL,
    consumer_number character varying(50),
    role character varying(20) NOT NULL,
    language_preference character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.user_management_customuser OWNER TO suvidha_user;

--
-- Name: user_management_customuser_groups; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.user_management_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_management_customuser_groups OWNER TO suvidha_user;

--
-- Name: user_management_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.user_management_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_management_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_management_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.user_management_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_management_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_management_customuser_user_permissions; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.user_management_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_management_customuser_user_permissions OWNER TO suvidha_user;

--
-- Name: user_management_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.user_management_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_management_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_management_otpverification; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.user_management_otpverification (
    id bigint NOT NULL,
    otp_code character varying(6) NOT NULL,
    otp_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_verified boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_management_otpverification OWNER TO suvidha_user;

--
-- Name: user_management_otpverification_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.user_management_otpverification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_management_otpverification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_management_usersession; Type: TABLE; Schema: public; Owner: suvidha_user
--

CREATE TABLE public.user_management_usersession (
    id bigint NOT NULL,
    token character varying(500) NOT NULL,
    ip_address inet,
    device_info text NOT NULL,
    last_activity timestamp with time zone NOT NULL,
    logout_time timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_management_usersession OWNER TO suvidha_user;

--
-- Name: user_management_usersession_id_seq; Type: SEQUENCE; Schema: public; Owner: suvidha_user
--

ALTER TABLE public.user_management_usersession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_management_usersession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audit_apiaccesslog; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.audit_apiaccesslog (id, endpoint, method, ip_address, response_status, "timestamp", user_id) FROM stdin;
\.


--
-- Data for Name: audit_auditlog; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.audit_auditlog (id, action_type, entity_type, entity_id, ip_address, details, "timestamp", user_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Blacklisted Token	6	add_blacklistedtoken
22	Can change Blacklisted Token	6	change_blacklistedtoken
23	Can delete Blacklisted Token	6	delete_blacklistedtoken
24	Can view Blacklisted Token	6	view_blacklistedtoken
25	Can add Outstanding Token	7	add_outstandingtoken
26	Can change Outstanding Token	7	change_outstandingtoken
27	Can delete Outstanding Token	7	delete_outstandingtoken
28	Can view Outstanding Token	7	view_outstandingtoken
29	Can add User	8	add_customuser
30	Can change User	8	change_customuser
31	Can delete User	8	delete_customuser
32	Can view User	8	view_customuser
33	Can add otp verification	9	add_otpverification
34	Can change otp verification	9	change_otpverification
35	Can delete otp verification	9	delete_otpverification
36	Can view otp verification	9	view_otpverification
37	Can add user session	10	add_usersession
38	Can change user session	10	change_usersession
39	Can delete user session	10	delete_usersession
40	Can view user session	10	view_usersession
41	Can add bill	11	add_bill
42	Can change bill	11	change_bill
43	Can delete bill	11	delete_bill
44	Can view bill	11	view_bill
45	Can add electricity account	12	add_electricityaccount
46	Can change electricity account	12	change_electricityaccount
47	Can delete electricity account	12	delete_electricityaccount
48	Can view electricity account	12	view_electricityaccount
49	Can add gas account	13	add_gasaccount
50	Can change gas account	13	change_gasaccount
51	Can delete gas account	13	delete_gasaccount
52	Can view gas account	13	view_gasaccount
53	Can add water account	14	add_wateraccount
54	Can change water account	14	change_wateraccount
55	Can delete water account	14	delete_wateraccount
56	Can view water account	14	view_wateraccount
57	Can add bill line item	15	add_billlineitem
58	Can change bill line item	15	change_billlineitem
59	Can delete bill line item	15	delete_billlineitem
60	Can view bill line item	15	view_billlineitem
61	Can add payment receipt	16	add_paymentreceipt
62	Can change payment receipt	16	change_paymentreceipt
63	Can delete payment receipt	16	delete_paymentreceipt
64	Can view payment receipt	16	view_paymentreceipt
65	Can add payment	17	add_payment
66	Can change payment	17	change_payment
67	Can delete payment	17	delete_payment
68	Can view payment	17	view_payment
69	Can add complaint	18	add_complaint
70	Can change complaint	18	change_complaint
71	Can delete complaint	18	delete_complaint
72	Can view complaint	18	view_complaint
73	Can add complaint attachment	19	add_complaintattachment
74	Can change complaint attachment	19	change_complaintattachment
75	Can delete complaint attachment	19	delete_complaintattachment
76	Can view complaint attachment	19	view_complaintattachment
77	Can add complaint update	20	add_complaintupdate
78	Can change complaint update	20	change_complaintupdate
79	Can delete complaint update	20	delete_complaintupdate
80	Can view complaint update	20	view_complaintupdate
81	Can add request document	21	add_requestdocument
82	Can change request document	21	change_requestdocument
83	Can delete request document	21	delete_requestdocument
84	Can view request document	21	view_requestdocument
85	Can add service request	22	add_servicerequest
86	Can change service request	22	change_servicerequest
87	Can delete service request	22	delete_servicerequest
88	Can view service request	22	view_servicerequest
89	Can add notification	23	add_notification
90	Can change notification	23	change_notification
91	Can delete notification	23	delete_notification
92	Can view notification	23	view_notification
93	Can add system alert	24	add_systemalert
94	Can change system alert	24	change_systemalert
95	Can delete system alert	24	delete_systemalert
96	Can view system alert	24	view_systemalert
97	Can add faq content	25	add_faqcontent
98	Can change faq content	25	change_faqcontent
99	Can delete faq content	25	delete_faqcontent
100	Can view faq content	25	view_faqcontent
101	Can add service content	26	add_servicecontent
102	Can change service content	26	change_servicecontent
103	Can delete service content	26	delete_servicecontent
104	Can view service content	26	view_servicecontent
105	Can add api access log	27	add_apiaccesslog
106	Can change api access log	27	change_apiaccesslog
107	Can delete api access log	27	delete_apiaccesslog
108	Can view api access log	27	view_apiaccesslog
109	Can add audit log	28	add_auditlog
110	Can change audit log	28	change_auditlog
111	Can delete audit log	28	delete_auditlog
112	Can view audit log	28	view_auditlog
113	Can add phone otp	29	add_phoneotp
114	Can change phone otp	29	change_phoneotp
115	Can delete phone otp	29	delete_phoneotp
116	Can view phone otp	29	view_phoneotp
117	Can add API key	30	add_apikey
118	Can change API key	30	change_apikey
119	Can delete API key	30	delete_apikey
120	Can view API key	30	view_apikey
\.


--
-- Data for Name: authentication_phoneotp; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.authentication_phoneotp (id, phone, otp, created_at, is_verified) FROM stdin;
1	1234567890	588223	2026-02-06 17:09:06.84501+00	t
2	9876543210	537016	2026-02-06 17:10:55.81898+00	t
4	7200136206	708875	2026-02-06 17:12:56.679768+00	f
\.


--
-- Data for Name: billing_bill; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.billing_bill (bill_id, account_type, consumer_number, bill_date, due_date, amount, arrears, status) FROM stdin;
\.


--
-- Data for Name: billing_billlineitem; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.billing_billlineitem (id, description, amount, quantity, bill_id) FROM stdin;
\.


--
-- Data for Name: billing_electricityaccount; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.billing_electricityaccount (id, consumer_number, account_holder, address, connection_type, meter_number, user_id) FROM stdin;
\.


--
-- Data for Name: billing_gasaccount; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.billing_gasaccount (id, consumer_number, account_holder, address, connection_type, user_id) FROM stdin;
\.


--
-- Data for Name: billing_wateraccount; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.billing_wateraccount (id, consumer_number, account_holder, address, connection_type, user_id) FROM stdin;
\.


--
-- Data for Name: content_faqcontent; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.content_faqcontent (id, category, language, question, answer) FROM stdin;
\.


--
-- Data for Name: content_servicecontent; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.content_servicecontent (id, service_type, language, title, description, is_active) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	token_blacklist	blacklistedtoken
7	token_blacklist	outstandingtoken
8	user_management	customuser
9	user_management	otpverification
10	user_management	usersession
11	billing	bill
12	billing	electricityaccount
13	billing	gasaccount
14	billing	wateraccount
15	billing	billlineitem
16	payments	paymentreceipt
17	payments	payment
18	grievances	complaint
19	grievances	complaintattachment
20	grievances	complaintupdate
21	service_requests	requestdocument
22	service_requests	servicerequest
23	notifications	notification
24	notifications	systemalert
25	content	faqcontent
26	content	servicecontent
27	audit	apiaccesslog
28	audit	auditlog
29	authentication	phoneotp
30	rest_framework_api_key	apikey
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-06 16:37:54.807167+00
2	contenttypes	0002_remove_content_type_name	2026-02-06 16:37:54.811147+00
3	auth	0001_initial	2026-02-06 16:37:54.840617+00
4	auth	0002_alter_permission_name_max_length	2026-02-06 16:37:54.844282+00
5	auth	0003_alter_user_email_max_length	2026-02-06 16:37:54.8479+00
6	auth	0004_alter_user_username_opts	2026-02-06 16:37:54.852098+00
7	auth	0005_alter_user_last_login_null	2026-02-06 16:37:54.856285+00
8	auth	0006_require_contenttypes_0002	2026-02-06 16:37:54.857857+00
9	auth	0007_alter_validators_add_error_messages	2026-02-06 16:37:54.860621+00
10	auth	0008_alter_user_username_max_length	2026-02-06 16:37:54.864662+00
11	auth	0009_alter_user_last_name_max_length	2026-02-06 16:37:54.868647+00
12	auth	0010_alter_group_name_max_length	2026-02-06 16:37:54.87254+00
13	auth	0011_update_proxy_permissions	2026-02-06 16:37:54.876598+00
14	auth	0012_alter_user_first_name_max_length	2026-02-06 16:37:54.880543+00
19	audit	0001_initial	2026-02-06 16:37:54.977022+00
21	billing	0001_initial	2026-02-06 16:37:55.033636+00
23	content	0001_initial	2026-02-06 16:37:55.075891+00
24	grievances	0001_initial	2026-02-06 16:37:55.10247+00
26	notifications	0001_initial	2026-02-06 16:37:55.156396+00
28	payments	0001_initial	2026-02-06 16:37:55.190563+00
30	service_requests	0001_initial	2026-02-06 16:37:55.231809+00
32	sessions	0001_initial	2026-02-06 16:37:55.269347+00
45	user_management	0001_initial	2026-02-06 16:55:38.339023+00
46	admin	0001_initial	2026-02-06 16:55:38.349334+00
47	admin	0002_logentry_remove_auto_add	2026-02-06 16:55:38.35549+00
48	admin	0003_logentry_add_action_flag_choices	2026-02-06 16:55:38.36208+00
49	audit	0002_initial	2026-02-06 16:55:38.379662+00
50	billing	0002_initial	2026-02-06 16:55:38.4028+00
51	grievances	0002_initial	2026-02-06 16:55:38.438265+00
52	notifications	0002_initial	2026-02-06 16:55:38.449501+00
53	payments	0002_initial	2026-02-06 16:55:38.474204+00
54	service_requests	0002_initial	2026-02-06 16:55:38.499233+00
55	token_blacklist	0001_initial	2026-02-06 16:55:38.522103+00
56	token_blacklist	0002_outstandingtoken_jti_hex	2026-02-06 16:55:38.533406+00
57	token_blacklist	0003_auto_20171017_2007	2026-02-06 16:55:38.548446+00
58	authentication	0001_initial	2026-02-06 17:08:18.905683+00
59	token_blacklist	0004_auto_20171017_2013	2026-02-07 05:27:41.962816+00
60	token_blacklist	0005_remove_outstandingtoken_jti	2026-02-07 05:27:44.891745+00
61	token_blacklist	0006_auto_20171017_2113	2026-02-07 05:27:44.905865+00
62	token_blacklist	0007_auto_20171017_2214	2026-02-07 05:27:44.936398+00
63	token_blacklist	0008_migrate_to_bigautofield	2026-02-07 05:27:44.960028+00
64	token_blacklist	0010_fix_migrate_to_bigautofield	2026-02-07 05:27:44.977974+00
65	token_blacklist	0011_linearizes_history	2026-02-07 05:27:44.980067+00
66	token_blacklist	0012_alter_outstandingtoken_user	2026-02-07 05:27:44.994449+00
67	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-02-07 05:27:45.009076+00
73	rest_framework_api_key	0001_initial	2026-02-07 09:48:53.027335+00
74	rest_framework_api_key	0002_auto_20190529_2243	2026-02-07 09:48:53.031755+00
75	rest_framework_api_key	0003_auto_20190623_1952	2026-02-07 09:48:53.034127+00
76	rest_framework_api_key	0004_prefix_hashed_key	2026-02-07 09:48:53.05808+00
77	rest_framework_api_key	0005_auto_20220110_1102	2026-02-07 09:48:53.061871+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: grievances_complaint; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.grievances_complaint (id, complaint_id, service_type, category, description, priority, status, created_at, resolved_at, user_id) FROM stdin;
\.


--
-- Data for Name: grievances_complaintattachment; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.grievances_complaintattachment (id, file_path, uploaded_at, complaint_id) FROM stdin;
\.


--
-- Data for Name: grievances_complaintupdate; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.grievances_complaintupdate (id, status, remarks, "timestamp", complaint_id, updated_by_id) FROM stdin;
\.


--
-- Data for Name: notifications_notification; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.notifications_notification (id, title, message, notification_type, is_read, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: notifications_systemalert; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.notifications_systemalert (id, alert_type, title, message, severity, is_active, created_at, expires_at) FROM stdin;
\.


--
-- Data for Name: payments_payment; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.payments_payment (id, payment_id, amount, payment_method, transaction_id, gateway_reference, status, "timestamp", bill_id, user_id) FROM stdin;
\.


--
-- Data for Name: payments_paymentreceipt; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.payments_paymentreceipt (id, receipt_number, receipt_data, generated_at, payment_id) FROM stdin;
\.


--
-- Data for Name: rest_framework_api_key_apikey; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.rest_framework_api_key_apikey (id, created, name, revoked, expiry_date, hashed_key, prefix) FROM stdin;
cjlNKxem.sha512$$b6b3e02825092f79966598bb19cc0cc28294d398d225ea6a01a73363f860f62b62222af8b9ec422d7924ce5761b48913297632e0312fb000ab22726a40c73284	2026-02-07 09:49:22.671044+00	Kiosk-Access-Key	f	\N	sha512$$b6b3e02825092f79966598bb19cc0cc28294d398d225ea6a01a73363f860f62b62222af8b9ec422d7924ce5761b48913297632e0312fb000ab22726a40c73284	cjlNKxem
5X05ih05.sha512$$ed546eb6158a57c0d8cd680491047b056aec8699a39e8ce0317e030b225ef37f6874e42cd3ede890242011f44ce019c1331c53f2dc48e8c421376ab58f475f85	2026-02-07 09:51:08.246325+00	Kiosk-Access-Key	f	\N	sha512$$ed546eb6158a57c0d8cd680491047b056aec8699a39e8ce0317e030b225ef37f6874e42cd3ede890242011f44ce019c1331c53f2dc48e8c421376ab58f475f85	5X05ih05
\.


--
-- Data for Name: service_requests_requestdocument; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.service_requests_requestdocument (id, document_type, file_path, uploaded_at, service_request_id) FROM stdin;
\.


--
-- Data for Name: service_requests_servicerequest; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.service_requests_servicerequest (id, request_id, service_type, request_type, details, status, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDcxMjMxMCwiaWF0IjoxNzcwNjI1OTEwLCJqdGkiOiI2OTUxMjM1MTBjZDE0YWFhYjFkZjcwYzcyYWIyMThjMSIsInVzZXJfaWQiOiI1In0.rqhmEp-KyDkjab6AR3uXG739tx7FsBL4Of7qlFzgA7E	2026-02-09 08:31:50.645829+00	2026-02-10 08:31:50+00	5	695123510cd14aaab1df70c72ab218c1
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDcxMjMxMCwiaWF0IjoxNzcwNjI1OTEwLCJqdGkiOiJhODM0ZjhkMWMxMmY0YjkxOGFlYjA3YjZiOTJmOTFlOSIsInVzZXJfaWQiOiI1In0.H8mddSeKCS7_kuER-Gga_Bs25hCl-28eVprHVLHGlpw	2026-02-09 08:31:50.708812+00	2026-02-10 08:31:50+00	5	a834f8d1c12f4b918aeb07b6b92f91e9
\.


--
-- Data for Name: user_management_customuser; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.user_management_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone, consumer_number, role, language_preference, created_at) FROM stdin;
1		\N	f	mock_citizen				f	t	2026-02-06 16:56:07.552336+00	9876543210	1234567890	CITIZEN	en	2026-02-06 16:56:07.552595+00
2		\N	f	citizen_9949954854				f	t	2026-02-06 16:59:52.888694+00	9949954854	\N	CITIZEN	en	2026-02-06 16:59:52.888865+00
3		\N	f	user_1234567890				f	t	2026-02-06 17:09:06.856242+00	1234567890	\N	CITIZEN	en	2026-02-06 17:09:06.856394+00
4		\N	f	user_7200136206				f	t	2026-02-06 17:11:26.262478+00	7200136206	\N	CITIZEN	en	2026-02-06 17:11:26.262641+00
5		\N	f	verify_user				f	t	2026-02-09 08:31:50.571598+00	9988776655	CN12345678	CITIZEN	en	2026-02-09 08:31:50.571835+00
\.


--
-- Data for Name: user_management_customuser_groups; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.user_management_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: user_management_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.user_management_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: user_management_otpverification; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.user_management_otpverification (id, otp_code, otp_type, created_at, expires_at, is_verified, user_id) FROM stdin;
1	781906	LOGIN	2026-02-06 16:56:07.559054+00	2026-02-06 17:01:07.55762+00	t	1
2	426882	LOGIN	2026-02-06 16:59:52.894898+00	2026-02-06 17:04:52.893429+00	t	2
3	265903	LOGIN	2026-02-09 08:31:50.637393+00	2026-02-09 08:36:50.635188+00	t	5
4	263131	LOGIN	2026-02-09 08:31:50.702375+00	2026-02-09 08:36:50.701535+00	t	5
\.


--
-- Data for Name: user_management_usersession; Type: TABLE DATA; Schema: public; Owner: suvidha_user
--

COPY public.user_management_usersession (id, token, ip_address, device_info, last_activity, logout_time, created_at, user_id) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90e	127.0.0.1	Unknown	2026-02-06 16:59:52.93184+00	\N	2026-02-06 16:59:52.931849+00	2
\.


--
-- Name: audit_apiaccesslog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.audit_apiaccesslog_id_seq', 1, false);


--
-- Name: audit_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.audit_auditlog_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 120, true);


--
-- Name: authentication_phoneotp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.authentication_phoneotp_id_seq', 4, true);


--
-- Name: billing_billlineitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.billing_billlineitem_id_seq', 1, false);


--
-- Name: billing_electricityaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.billing_electricityaccount_id_seq', 1, false);


--
-- Name: billing_gasaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.billing_gasaccount_id_seq', 1, false);


--
-- Name: billing_wateraccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.billing_wateraccount_id_seq', 1, false);


--
-- Name: content_faqcontent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.content_faqcontent_id_seq', 1, false);


--
-- Name: content_servicecontent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.content_servicecontent_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 30, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 77, true);


--
-- Name: grievances_complaint_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.grievances_complaint_id_seq', 1, false);


--
-- Name: grievances_complaintattachment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.grievances_complaintattachment_id_seq', 1, false);


--
-- Name: grievances_complaintupdate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.grievances_complaintupdate_id_seq', 1, false);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.notifications_notification_id_seq', 1, false);


--
-- Name: notifications_systemalert_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.notifications_systemalert_id_seq', 1, false);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.payments_payment_id_seq', 1, false);


--
-- Name: payments_paymentreceipt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.payments_paymentreceipt_id_seq', 1, false);


--
-- Name: service_requests_requestdocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.service_requests_requestdocument_id_seq', 1, false);


--
-- Name: service_requests_servicerequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.service_requests_servicerequest_id_seq', 1, false);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 6, true);


--
-- Name: user_management_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.user_management_customuser_groups_id_seq', 1, false);


--
-- Name: user_management_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.user_management_customuser_id_seq', 5, true);


--
-- Name: user_management_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.user_management_customuser_user_permissions_id_seq', 1, false);


--
-- Name: user_management_otpverification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.user_management_otpverification_id_seq', 4, true);


--
-- Name: user_management_usersession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: suvidha_user
--

SELECT pg_catalog.setval('public.user_management_usersession_id_seq', 1, true);


--
-- Name: audit_apiaccesslog audit_apiaccesslog_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.audit_apiaccesslog
    ADD CONSTRAINT audit_apiaccesslog_pkey PRIMARY KEY (id);


--
-- Name: audit_auditlog audit_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.audit_auditlog
    ADD CONSTRAINT audit_auditlog_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_phoneotp authentication_phoneotp_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.authentication_phoneotp
    ADD CONSTRAINT authentication_phoneotp_pkey PRIMARY KEY (id);


--
-- Name: billing_bill billing_bill_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_bill
    ADD CONSTRAINT billing_bill_pkey PRIMARY KEY (bill_id);


--
-- Name: billing_billlineitem billing_billlineitem_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_billlineitem
    ADD CONSTRAINT billing_billlineitem_pkey PRIMARY KEY (id);


--
-- Name: billing_electricityaccount billing_electricityaccount_consumer_number_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_electricityaccount
    ADD CONSTRAINT billing_electricityaccount_consumer_number_key UNIQUE (consumer_number);


--
-- Name: billing_electricityaccount billing_electricityaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_electricityaccount
    ADD CONSTRAINT billing_electricityaccount_pkey PRIMARY KEY (id);


--
-- Name: billing_gasaccount billing_gasaccount_consumer_number_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_gasaccount
    ADD CONSTRAINT billing_gasaccount_consumer_number_key UNIQUE (consumer_number);


--
-- Name: billing_gasaccount billing_gasaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_gasaccount
    ADD CONSTRAINT billing_gasaccount_pkey PRIMARY KEY (id);


--
-- Name: billing_wateraccount billing_wateraccount_consumer_number_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_wateraccount
    ADD CONSTRAINT billing_wateraccount_consumer_number_key UNIQUE (consumer_number);


--
-- Name: billing_wateraccount billing_wateraccount_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_wateraccount
    ADD CONSTRAINT billing_wateraccount_pkey PRIMARY KEY (id);


--
-- Name: content_faqcontent content_faqcontent_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.content_faqcontent
    ADD CONSTRAINT content_faqcontent_pkey PRIMARY KEY (id);


--
-- Name: content_servicecontent content_servicecontent_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.content_servicecontent
    ADD CONSTRAINT content_servicecontent_pkey PRIMARY KEY (id);


--
-- Name: content_servicecontent content_servicecontent_service_type_language_d096626b_uniq; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.content_servicecontent
    ADD CONSTRAINT content_servicecontent_service_type_language_d096626b_uniq UNIQUE (service_type, language);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: grievances_complaint grievances_complaint_complaint_id_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaint
    ADD CONSTRAINT grievances_complaint_complaint_id_key UNIQUE (complaint_id);


--
-- Name: grievances_complaint grievances_complaint_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaint
    ADD CONSTRAINT grievances_complaint_pkey PRIMARY KEY (id);


--
-- Name: grievances_complaintattachment grievances_complaintattachment_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaintattachment
    ADD CONSTRAINT grievances_complaintattachment_pkey PRIMARY KEY (id);


--
-- Name: grievances_complaintupdate grievances_complaintupdate_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaintupdate
    ADD CONSTRAINT grievances_complaintupdate_pkey PRIMARY KEY (id);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: notifications_systemalert notifications_systemalert_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.notifications_systemalert
    ADD CONSTRAINT notifications_systemalert_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_payment_id_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_payment_id_key UNIQUE (payment_id);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: payments_paymentreceipt payments_paymentreceipt_payment_id_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_paymentreceipt
    ADD CONSTRAINT payments_paymentreceipt_payment_id_key UNIQUE (payment_id);


--
-- Name: payments_paymentreceipt payments_paymentreceipt_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_paymentreceipt
    ADD CONSTRAINT payments_paymentreceipt_pkey PRIMARY KEY (id);


--
-- Name: payments_paymentreceipt payments_paymentreceipt_receipt_number_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_paymentreceipt
    ADD CONSTRAINT payments_paymentreceipt_receipt_number_key UNIQUE (receipt_number);


--
-- Name: rest_framework_api_key_apikey rest_framework_api_key_apikey_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.rest_framework_api_key_apikey
    ADD CONSTRAINT rest_framework_api_key_apikey_pkey PRIMARY KEY (id);


--
-- Name: rest_framework_api_key_apikey rest_framework_api_key_apikey_prefix_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.rest_framework_api_key_apikey
    ADD CONSTRAINT rest_framework_api_key_apikey_prefix_key UNIQUE (prefix);


--
-- Name: service_requests_requestdocument service_requests_requestdocument_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.service_requests_requestdocument
    ADD CONSTRAINT service_requests_requestdocument_pkey PRIMARY KEY (id);


--
-- Name: service_requests_servicerequest service_requests_servicerequest_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.service_requests_servicerequest
    ADD CONSTRAINT service_requests_servicerequest_pkey PRIMARY KEY (id);


--
-- Name: service_requests_servicerequest service_requests_servicerequest_request_id_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.service_requests_servicerequest
    ADD CONSTRAINT service_requests_servicerequest_request_id_key UNIQUE (request_id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: user_management_customuser_groups user_management_customus_customuser_id_group_id_5c501b9c_uniq; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_groups
    ADD CONSTRAINT user_management_customus_customuser_id_group_id_5c501b9c_uniq UNIQUE (customuser_id, group_id);


--
-- Name: user_management_customuser_user_permissions user_management_customus_customuser_id_permission_e37ca3bb_uniq; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_user_permissions
    ADD CONSTRAINT user_management_customus_customuser_id_permission_e37ca3bb_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: user_management_customuser user_management_customuser_consumer_number_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser
    ADD CONSTRAINT user_management_customuser_consumer_number_key UNIQUE (consumer_number);


--
-- Name: user_management_customuser_groups user_management_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_groups
    ADD CONSTRAINT user_management_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: user_management_customuser user_management_customuser_phone_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser
    ADD CONSTRAINT user_management_customuser_phone_key UNIQUE (phone);


--
-- Name: user_management_customuser user_management_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser
    ADD CONSTRAINT user_management_customuser_pkey PRIMARY KEY (id);


--
-- Name: user_management_customuser_user_permissions user_management_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_user_permissions
    ADD CONSTRAINT user_management_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_management_customuser user_management_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser
    ADD CONSTRAINT user_management_customuser_username_key UNIQUE (username);


--
-- Name: user_management_otpverification user_management_otpverification_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_otpverification
    ADD CONSTRAINT user_management_otpverification_pkey PRIMARY KEY (id);


--
-- Name: user_management_usersession user_management_usersession_pkey; Type: CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_usersession
    ADD CONSTRAINT user_management_usersession_pkey PRIMARY KEY (id);


--
-- Name: audit_apiaccesslog_user_id_f374bec2; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX audit_apiaccesslog_user_id_f374bec2 ON public.audit_apiaccesslog USING btree (user_id);


--
-- Name: audit_auditlog_user_id_c1cca96c; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX audit_auditlog_user_id_c1cca96c ON public.audit_auditlog USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: billing_bill_bill_id_4f2e599a_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_bill_bill_id_4f2e599a_like ON public.billing_bill USING btree (bill_id varchar_pattern_ops);


--
-- Name: billing_billlineitem_bill_id_6b4a7b9a; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_billlineitem_bill_id_6b4a7b9a ON public.billing_billlineitem USING btree (bill_id);


--
-- Name: billing_billlineitem_bill_id_6b4a7b9a_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_billlineitem_bill_id_6b4a7b9a_like ON public.billing_billlineitem USING btree (bill_id varchar_pattern_ops);


--
-- Name: billing_electricityaccount_consumer_number_ae5ad6bf_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_electricityaccount_consumer_number_ae5ad6bf_like ON public.billing_electricityaccount USING btree (consumer_number varchar_pattern_ops);


--
-- Name: billing_electricityaccount_user_id_ac82aecd; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_electricityaccount_user_id_ac82aecd ON public.billing_electricityaccount USING btree (user_id);


--
-- Name: billing_gasaccount_consumer_number_2e0cb179_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_gasaccount_consumer_number_2e0cb179_like ON public.billing_gasaccount USING btree (consumer_number varchar_pattern_ops);


--
-- Name: billing_gasaccount_user_id_03acdb07; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_gasaccount_user_id_03acdb07 ON public.billing_gasaccount USING btree (user_id);


--
-- Name: billing_wateraccount_consumer_number_b82832f6_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_wateraccount_consumer_number_b82832f6_like ON public.billing_wateraccount USING btree (consumer_number varchar_pattern_ops);


--
-- Name: billing_wateraccount_user_id_7a0721b8; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX billing_wateraccount_user_id_7a0721b8 ON public.billing_wateraccount USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: grievances_complaint_complaint_id_423d0e20_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX grievances_complaint_complaint_id_423d0e20_like ON public.grievances_complaint USING btree (complaint_id varchar_pattern_ops);


--
-- Name: grievances_complaint_user_id_8d094a9a; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX grievances_complaint_user_id_8d094a9a ON public.grievances_complaint USING btree (user_id);


--
-- Name: grievances_complaintattachment_complaint_id_f4110495; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX grievances_complaintattachment_complaint_id_f4110495 ON public.grievances_complaintattachment USING btree (complaint_id);


--
-- Name: grievances_complaintupdate_complaint_id_8ad9e29f; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX grievances_complaintupdate_complaint_id_8ad9e29f ON public.grievances_complaintupdate USING btree (complaint_id);


--
-- Name: grievances_complaintupdate_updated_by_id_84604e85; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX grievances_complaintupdate_updated_by_id_84604e85 ON public.grievances_complaintupdate USING btree (updated_by_id);


--
-- Name: notifications_notification_user_id_b5e8c0ff; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX notifications_notification_user_id_b5e8c0ff ON public.notifications_notification USING btree (user_id);


--
-- Name: payments_payment_bill_id_80d854b4; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX payments_payment_bill_id_80d854b4 ON public.payments_payment USING btree (bill_id);


--
-- Name: payments_payment_bill_id_80d854b4_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX payments_payment_bill_id_80d854b4_like ON public.payments_payment USING btree (bill_id varchar_pattern_ops);


--
-- Name: payments_payment_payment_id_5ab18190_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX payments_payment_payment_id_5ab18190_like ON public.payments_payment USING btree (payment_id varchar_pattern_ops);


--
-- Name: payments_payment_user_id_f9db060a; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX payments_payment_user_id_f9db060a ON public.payments_payment USING btree (user_id);


--
-- Name: payments_paymentreceipt_receipt_number_d501047c_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX payments_paymentreceipt_receipt_number_d501047c_like ON public.payments_paymentreceipt USING btree (receipt_number varchar_pattern_ops);


--
-- Name: rest_framework_api_key_apikey_created_c61872d9; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX rest_framework_api_key_apikey_created_c61872d9 ON public.rest_framework_api_key_apikey USING btree (created);


--
-- Name: rest_framework_api_key_apikey_id_6e07e68e_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX rest_framework_api_key_apikey_id_6e07e68e_like ON public.rest_framework_api_key_apikey USING btree (id varchar_pattern_ops);


--
-- Name: rest_framework_api_key_apikey_prefix_4e0db5f8_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX rest_framework_api_key_apikey_prefix_4e0db5f8_like ON public.rest_framework_api_key_apikey USING btree (prefix varchar_pattern_ops);


--
-- Name: service_requests_requestdocument_service_request_id_82ddd734; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX service_requests_requestdocument_service_request_id_82ddd734 ON public.service_requests_requestdocument USING btree (service_request_id);


--
-- Name: service_requests_servicerequest_request_id_cc94b525_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX service_requests_servicerequest_request_id_cc94b525_like ON public.service_requests_servicerequest USING btree (request_id varchar_pattern_ops);


--
-- Name: service_requests_servicerequest_user_id_cbd3cb6e; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX service_requests_servicerequest_user_id_cbd3cb6e ON public.service_requests_servicerequest USING btree (user_id);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: user_management_customuser_consumer_number_dfbe78fa_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_consumer_number_dfbe78fa_like ON public.user_management_customuser USING btree (consumer_number varchar_pattern_ops);


--
-- Name: user_management_customuser_customuser_id_955b4f91; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_customuser_id_955b4f91 ON public.user_management_customuser_user_permissions USING btree (customuser_id);


--
-- Name: user_management_customuser_groups_customuser_id_66e96b95; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_groups_customuser_id_66e96b95 ON public.user_management_customuser_groups USING btree (customuser_id);


--
-- Name: user_management_customuser_groups_group_id_89c2ce00; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_groups_group_id_89c2ce00 ON public.user_management_customuser_groups USING btree (group_id);


--
-- Name: user_management_customuser_permission_id_6b578585; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_permission_id_6b578585 ON public.user_management_customuser_user_permissions USING btree (permission_id);


--
-- Name: user_management_customuser_phone_729614f6_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_phone_729614f6_like ON public.user_management_customuser USING btree (phone varchar_pattern_ops);


--
-- Name: user_management_customuser_username_f8c22f22_like; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_customuser_username_f8c22f22_like ON public.user_management_customuser USING btree (username varchar_pattern_ops);


--
-- Name: user_management_otpverification_user_id_b2c15306; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_otpverification_user_id_b2c15306 ON public.user_management_otpverification USING btree (user_id);


--
-- Name: user_management_usersession_user_id_49ba3ec9; Type: INDEX; Schema: public; Owner: suvidha_user
--

CREATE INDEX user_management_usersession_user_id_49ba3ec9 ON public.user_management_usersession USING btree (user_id);


--
-- Name: audit_apiaccesslog audit_apiaccesslog_user_id_f374bec2_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.audit_apiaccesslog
    ADD CONSTRAINT audit_apiaccesslog_user_id_f374bec2_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_auditlog audit_auditlog_user_id_c1cca96c_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.audit_auditlog
    ADD CONSTRAINT audit_auditlog_user_id_c1cca96c_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: billing_billlineitem billing_billlineitem_bill_id_6b4a7b9a_fk_billing_bill_bill_id; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_billlineitem
    ADD CONSTRAINT billing_billlineitem_bill_id_6b4a7b9a_fk_billing_bill_bill_id FOREIGN KEY (bill_id) REFERENCES public.billing_bill(bill_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: billing_electricityaccount billing_electricitya_user_id_ac82aecd_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_electricityaccount
    ADD CONSTRAINT billing_electricitya_user_id_ac82aecd_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: billing_gasaccount billing_gasaccount_user_id_03acdb07_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_gasaccount
    ADD CONSTRAINT billing_gasaccount_user_id_03acdb07_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: billing_wateraccount billing_wateraccount_user_id_7a0721b8_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.billing_wateraccount
    ADD CONSTRAINT billing_wateraccount_user_id_7a0721b8_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grievances_complaintupdate grievances_complaint_complaint_id_8ad9e29f_fk_grievance; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaintupdate
    ADD CONSTRAINT grievances_complaint_complaint_id_8ad9e29f_fk_grievance FOREIGN KEY (complaint_id) REFERENCES public.grievances_complaint(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grievances_complaintattachment grievances_complaint_complaint_id_f4110495_fk_grievance; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaintattachment
    ADD CONSTRAINT grievances_complaint_complaint_id_f4110495_fk_grievance FOREIGN KEY (complaint_id) REFERENCES public.grievances_complaint(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grievances_complaintupdate grievances_complaint_updated_by_id_84604e85_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaintupdate
    ADD CONSTRAINT grievances_complaint_updated_by_id_84604e85_fk_user_mana FOREIGN KEY (updated_by_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grievances_complaint grievances_complaint_user_id_8d094a9a_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.grievances_complaint
    ADD CONSTRAINT grievances_complaint_user_id_8d094a9a_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notifi_user_id_b5e8c0ff_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_user_id_b5e8c0ff_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_bill_id_80d854b4_fk_billing_bill_bill_id; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_bill_id_80d854b4_fk_billing_bill_bill_id FOREIGN KEY (bill_id) REFERENCES public.billing_bill(bill_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_user_id_f9db060a_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_user_id_f9db060a_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_paymentreceipt payments_paymentrece_payment_id_979ee6a3_fk_payments_; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.payments_paymentreceipt
    ADD CONSTRAINT payments_paymentrece_payment_id_979ee6a3_fk_payments_ FOREIGN KEY (payment_id) REFERENCES public.payments_payment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: service_requests_requestdocument service_requests_req_service_request_id_82ddd734_fk_service_r; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.service_requests_requestdocument
    ADD CONSTRAINT service_requests_req_service_request_id_82ddd734_fk_service_r FOREIGN KEY (service_request_id) REFERENCES public.service_requests_servicerequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: service_requests_servicerequest service_requests_ser_user_id_cbd3cb6e_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.service_requests_servicerequest
    ADD CONSTRAINT service_requests_ser_user_id_cbd3cb6e_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_management_customuser_groups user_management_cust_customuser_id_66e96b95_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_groups
    ADD CONSTRAINT user_management_cust_customuser_id_66e96b95_fk_user_mana FOREIGN KEY (customuser_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_management_customuser_user_permissions user_management_cust_customuser_id_955b4f91_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_user_permissions
    ADD CONSTRAINT user_management_cust_customuser_id_955b4f91_fk_user_mana FOREIGN KEY (customuser_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_management_customuser_groups user_management_cust_group_id_89c2ce00_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_groups
    ADD CONSTRAINT user_management_cust_group_id_89c2ce00_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_management_customuser_user_permissions user_management_cust_permission_id_6b578585_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_customuser_user_permissions
    ADD CONSTRAINT user_management_cust_permission_id_6b578585_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_management_otpverification user_management_otpv_user_id_b2c15306_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_otpverification
    ADD CONSTRAINT user_management_otpv_user_id_b2c15306_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_management_usersession user_management_user_user_id_49ba3ec9_fk_user_mana; Type: FK CONSTRAINT; Schema: public; Owner: suvidha_user
--

ALTER TABLE ONLY public.user_management_usersession
    ADD CONSTRAINT user_management_user_user_id_49ba3ec9_fk_user_mana FOREIGN KEY (user_id) REFERENCES public.user_management_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: suvidha_user
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict D0j0grVEmedvbrUY3epnhHutEi1ciFtAlzpQ8NXgac3Yg8YXaT6LyXADxQhPQFw

