export const SUPPORTED_LANGUAGES = [
  { id: 'en', name: 'English', native: 'English' },
  { id: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { id: 'bn', name: 'Bengali', native: 'বাংলা' },
  { id: 'te', name: 'Telugu', native: 'తెలుగు' },
  { id: 'mr', name: 'Marathi', native: 'मराठी' },
  { id: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { id: 'ur', name: 'Urdu', native: 'اردو' },
  { id: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { id: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { id: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { id: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { id: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { id: 'as', name: 'Assamese', native: 'অসমীয়া' },
  { id: 'mai', name: 'Maithili', native: 'मैथिली' },
  { id: 'ks', name: 'Kashmiri', native: 'کٲشور' },
  { id: 'sd', name: 'Sindhi', native: 'سنڌي' },
  { id: 'kok', name: 'Konkani', native: 'कोंकणी' },
  { id: 'mni', name: 'Manipuri', native: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { id: 'ne', name: 'Nepali', native: 'नेपाली' },
  { id: 'brx', name: 'Bodo', native: 'बर’' },
  { id: 'doi', name: 'Dogri', native: 'डोगरी' },
  { id: 'sa', name: 'Sanskrit', native: 'संस्कृतम्' },
  { id: 'sat', name: 'Santhali', native: 'ᱥᱟᱱᱛᱟᱲᱤ' },
] as const;

export type LanguageId = (typeof SUPPORTED_LANGUAGES)[number]['id'];

const CORE_KEYS = {
  welcome: {
    en: 'Welcome to SUVIDHA Kiosk',
    hi: 'सुविधा कियोस्क में स्वागत है',
    bn: 'সুবিধা কিয়স্কে স্বাগতম',
    te: 'సువిధ కియోస్క్‌కి స్వాగతం',
    mr: 'सुविधा किओस्कमध्ये स्वागत आहे',
    ta: 'சுவிதா கியோஸ்கிற்கு வரவேற்கிறோம்',
    ur: 'سودھا کیوسک میں خوش آمدید',
    gu: 'સુવિધા કિઓસ્કમાં સ્વાગત છે',
    kn: 'ಸುವಿಧಾ ಕಿಯೋಸ್ಕ್‌ಗೆ ಸುಸ್ವಾಗತ',
    ml: 'സുവിധ കിയോസ്കിലേക്ക് സ്വാഗതം',
    or: 'ସୁବିଧା କିଓସ୍କକୁ ସ୍ୱାଗତ',
    pa: 'ਸੁਵਿਧਾ ਕਿਓਸਕ ਵਿੱਚ ਸੁਆਗਤ ਹੈ',
    as: 'সুবিধা কিয়স্কলৈ স্বাগতম',
    mai: 'सुविधा कियोस्क मे स्वागत अछि',
    ks: 'سودھا کیوسک منز خوش آمدید',
    sd: 'سودھا ڪيوسڪ ۾ ڀليڪار',
    kok: 'सुविधा कियोस्कांत येवकार',
    mni: 'সুবিধা কিওস্কতা তরাম্না ওকচরি',
    ne: 'सुविधा कियोस्कमा स्वागत छ',
    brx: 'सुबिदा कियस्क आव बरायबाय',
    doi: 'सुविधा कियोस्क च स्वागत ऐ',
    sa: 'सुलभा-कियोस्क-मध्ये स्वागतम्',
    sat: 'ᱥᱩᱵᱤᱫᱷᱟ ᱠᱤᱭᱳᱥᱠ ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
  },
  pay_bill: {
    en: 'Pay Your Bill',
    hi: 'बिल भुगतान',
    bn: 'বিল পরিশোধ',
    te: 'బిల్లు చెల్లింపు',
    mr: 'बिल भरा',
    ta: 'கட்டணம் செலுத்துங்கள்',
    ur: 'بل ادا کریں',
    gu: 'બિલ ભરો',
    kn: 'ಬಿಲ್ ಪಾವತಿಸಿ',
    ml: 'ബില്ല് അടയ്ക്കുക',
    or: 'ବିଲ୍ ପୈଠ',
    pa: 'ਬਿੱਲ ਦਾ ਭੁਗਤਾਨ',
    as: 'বিল পৰিশোধ',
    mai: 'बिल भुगतान',
    ks: 'بل ادا کٔریو',
    sd: 'بل ادا ڪريو',
    kok: 'बील भरून घेयात',
    mni: 'বিল পীবীউ',
    ne: 'बिल तिर्नुहोस्',
    brx: 'बिल होनाय',
    doi: 'बिल पैसै देना',
    sa: 'शुल्कं ददातु',
    sat: 'ᱵᱤᱞ ᱮᱢ',
  },
  apply_new_connection: {
    en: 'Apply New Connection',
    hi: 'नया कनेक्शन',
    bn: 'নতুন সংযোগ',
    te: 'కొత్త కనెక్షన్',
    mr: 'नवीन कनेक्शन',
    ta: 'புதிய இணைப்பு',
    ur: 'نیا کنکشن',
    gu: 'નવું કનેક્શન',
    kn: 'ಹೊಸ ಸಂಪರ್ಕ',
    ml: 'പുതിയ കണക്ഷൻ',
    or: 'ନୂତନ ସଂଯୋଗ',
    pa: 'ਨਵਾਂ ਕਨੈਕਸ਼ਨ',
    as: 'নতুন সংযোগ',
    mai: 'नब जडान',
    ks: 'نۆ کنکشن',
    sd: 'نئون ڪنيڪشن',
    kok: 'नवो जोडणी',
    mni: 'অনৌবা কন্নেক্সন',
    ne: 'नयाँ जडान',
    brx: 'गोदान फोनांजाब',
    doi: 'नमां कनेक्शन',
    sa: 'नूतन-सम्बन्धः',
    sat: 'ᱱᱟᱣᱟ ᱡᱚᱲᱟᱣ',
  },
  register_complaint: {
    en: 'Register Complaint',
    hi: 'शिकायत दर्ज करें',
    bn: 'অভিযোগ দায়ের',
    te: 'ఫిర్యాదు నమోదు',
    mr: 'तक्रार नोंदवा',
    ta: 'புகார் பதிவு',
    ur: 'شکایت درج کریں',
    gu: 'ફરિયાદ નોંધાવો',
    kn: 'ದೂರು ಸಲ್ಲಿಸಿ',
    ml: 'പരാതി നൽകുക',
    or: 'ଅଭିଯୋଗ ପଞ୍ଜିକରଣ',
    pa: 'ਸ਼ਿਕಾಯਤ ਦਰਜ ਕਰੋ',
    as: 'অভিযোগ পঞ্জীয়ন',
    mai: 'शिकायत दर्ज करू',
    ks: 'شکایت درج کٔریو',
    sd: 'شڪايت داخل ڪريو',
    kok: 'तक्रार नोंद करा',
    mni: 'ৱাকৎ লৌজিনবা',
    ne: 'गुनासो दर्ता',
    brx: 'अजद होनाय',
    doi: 'शकायत दर्ज करो',
    sa: 'परिवादं लिखतु',
    sat: 'ᱞᱟᱹᱞᱤᱥ ᱫᱚᱨᱡᱽ',
  },
  track_status: {
    en: 'Track My Request',
    hi: 'स्थिति ट्रैक करें',
    bn: 'অবস্থা ট্র্যাক',
    te: 'స్థితి ట్రాక్',
    mr: 'स्थिती तपासा',
    ta: 'நிலையை கண்காணியுங்கள்',
    ur: 'اسٹیٹس چیک کریں',
    gu: 'સ્થિતિ તપાસો',
    kn: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    ml: 'നില പരിശോധിക്കുക',
    or: 'ସ୍ଥିତି ଯାଞ୍ច',
    pa: 'ਸਥਿਤੀ ਦੀ ਜਾਂਚ',
    as: 'স্থিতি নিৰীক্ষণ',
    mai: 'स्थिति देखू',
    ks: 'حالت ژھانڈیو',
    sd: 'حالت چيڪ ڪريو',
    kok: 'स्थिती तपासात',
    mni: 'ফীভম চেক তৌবা',
    ne: 'स्थिति हेर्नुहोस्',
    brx: 'थाथाइ नायनाय',
    doi: 'हालत देखो',
    sa: 'स्थितिं पश्यतु',
    sat: 'ᱥᱛᱷᱤᱛᱤ ᱧᱮᱞ',
  },
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {};

// Initialize TRANSLATIONS object for all supported languages
SUPPORTED_LANGUAGES.forEach((lang) => {
  TRANSLATIONS[lang.id] = {
    logout: 'Logout',
    dashboard: 'Dashboard',
    success: 'Successful!',
    loading: 'Loading...',
    touch_to_start: 'Touch to Start',
    gate_way_title: 'Digital Gateway to Services',
    smart_city_services: 'Smart City Services',
    footer_belongings: 'Please take your belongings before leaving.',
    assisted_help: 'Help',
    citizen_services: 'Citizen Services',
    login_title: 'Sign In',
    mobile_no: 'Mobile Number',
    consumer_no: 'Consumer Number',
    get_otp: 'Get OTP',
    verify: 'Verify & Login',
    tracking_id: 'Tracking ID',
    status: 'Status',
    error_otp: 'Invalid OTP.',
    detected_region: 'Location',
    kill_kiosk: 'Kill Kiosk',
    tap_to_enter: 'Tap to Enter',
    submit: 'Submit',
    electricity: 'Electricity',
    water: 'Water',
    gas: 'Gas',
    domestic: 'Domestic',
    commercial: 'Commercial',
    industrial: 'Industrial',
    personal_details: 'Personal Details',
    applicant_name: 'Applicant Name',
    identity_proof: 'ID Proof Number',
    choose_service_desc: 'Select the utility type',
    choose_category_desc: 'Select connection category',
    select_service: 'Select Service',
    select_category: 'Select Category',
  };

  // Overlay core keys
  Object.keys(CORE_KEYS).forEach((key) => {
    const translations = CORE_KEYS[key as keyof typeof CORE_KEYS];
    if (translations[lang.id as keyof typeof translations]) {
      TRANSLATIONS[lang.id][key] = translations[lang.id as keyof typeof translations]!;
    }
  });
});

export const getTranslation = (id: string, key: string) => {
  return TRANSLATIONS[id]?.[key] || TRANSLATIONS['en']?.[key] || key;
};
