export const SUPPORTED_LANGUAGES = [
  { id: 'en', name: 'English', native: 'English' },
  { id: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { id: 'bn', name: 'Bengali', native: 'বাংলা' },
  { id: 'te', name: 'Telugu', native: 'తెలుగు' },
  { id: 'mr', name: 'Marathi', native: 'मराठी' },
  { id: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { id: 'ur', name: 'Urdu', native: 'اردو' },
  { id: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { id: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { id: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { id: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { id: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { id: 'as', name: 'Assamese', native: 'অসমীয়া' },
  { id: 'mai', name: 'Maithili', native: 'मैथिली' },
  { id: 'ks', name: 'Kashmiri', native: 'کٲشور' },
  { id: 'sd', name: 'Sindhi', native: 'سنڌي' },
  { id: 'kok', name: 'Konkani', native: 'कोंकणी' },
  { id: 'mni', name: 'Manipuri', native: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { id: 'ne', name: 'Nepali', native: 'नेपाली' },
  { id: 'brx', name: 'Bodo', native: 'बर’' },
  { id: 'doi', name: 'Dogri', native: 'डोगरी' },
  { id: 'sa', name: 'Sanskrit', native: 'संस्कृतम्' },
  { id: 'sat', name: 'Santhali', native: 'ᱥᱟᱱᱛᱟᱲᱤ' },
] as const;

export type LanguageId = (typeof SUPPORTED_LANGUAGES)[number]['id'];

const CORE_KEYS = {
  welcome: {
    en: 'Welcome to SUVIDHA Kiosk',
    hi: 'सुविधा कियोस्क में स्वागत है',
    bn: 'সুবিধা কিয়স্কে স্বাগতম',
    te: 'సువిధ కియోస్క్‌కి స్వాగతం',
    mr: 'सुविधा किओस्कमध्ये स्वागत आहे',
    ta: 'சுவிதா கியோஸ்கிற்கு வரவேற்கிறோம்',
    ur: 'سودھا کیوسک میں خوش آمدید',
    gu: 'સુવિધા કિઓસ્કમાં સ્વાગત છે',
    kn: 'ಸುವಿಧಾ ಕಿಯೋಸ್ಕ್‌ಗೆ ಸುಸ್ವಾಗತ',
    ml: 'സുവിധ കിയോസ്കിലേക്ക് സ്വാഗതം',
    or: 'ସୁବିଧା କିଓସ୍କକୁ ସ୍ୱାଗତ',
    pa: 'ਸੁਵਿਧਾ ਕਿਓਸਕ ਵਿੱਚ ਸੁਆਗਤ ਹੈ',
    as: 'সুবিধা কিয়স্কলৈ স্বাগতম',
    mai: 'सुविधा कियोस्क मे स्वागत अछि',
    ks: 'سودھا کیوسک منز خوش آمدید',
    sd: 'سودھا ڪيوسڪ ۾ ڀليڪار',
    kok: 'सुविधा कियोस्कांत येवकार',
    mni: 'সুবিধা কিওস্কতা তরাম্না ওকচরি',
    ne: 'सुविधा कियोस्कमा स्वागत छ',
    brx: 'सुबिदा कियस्क आव बरायबाय',
    doi: 'सुविधा कियोस्क च स्वागत ऐ',
    sa: 'सुलभा-कियोस्क-मध्ये स्वागतम्',
    sat: 'ᱥᱩᱵᱤᱫᱷᱟ ᱠᱤᱭᱳᱥᱠ ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
  },
  pay_bill: {
    en: 'Pay Your Bill',
    hi: 'बिल भुगतान',
    bn: 'বিল পরিশোধ',
    te: 'బిల్లు చెల్లింపు',
    mr: 'बिल भरा',
    ta: 'கட்டணம் செலுத்துங்கள்',
    ur: 'بل ادا کریں',
    gu: 'બિલ ભરો',
    kn: 'ಬಿಲ್ ಪಾವತಿಸಿ',
    ml: 'ബില്ല് അടയ്ക്കുക',
    or: 'ବିଲ୍ ପୈଠ',
    pa: 'ਬਿੱਲ ਦਾ ਭੁਗਤਾਨ',
    as: 'বিল পৰিশোধ',
    mai: 'बिल भुगतान',
    ks: 'بل ادا کٔریو',
    sd: 'بل ادا ڪريو',
    kok: 'बील भरून घेयात',
    mni: 'বিল পীবীউ',
    ne: 'बिल तिर्नुहोस्',
    brx: 'बिल होनाय',
    doi: 'बिल पैसै देना',
    sa: 'शुल्कं ददातु',
    sat: 'ᱵᱤᱞ ᱮᱢ',
  },
  apply_new_connection: {
    en: 'Apply New Connection',
    hi: 'नया कनेक्शन',
    bn: 'নতুন সংযোগ',
    te: 'కొత్త కనెక్షన్',
    mr: 'नवीन कनेक्शन',
    ta: 'புதிய இணைப்பு',
    ur: 'نیا کنکشن',
    gu: 'નવું કનેક્શન',
    kn: 'ಹೊಸ ಸಂಪರ್ಕ',
    ml: 'പുതിയ കണക്ഷൻ',
    or: 'ନୂତନ ସଂଯୋଗ',
    pa: 'ਨਵਾਂ ਕਨੈਕਸ਼ਨ',
    as: 'নতুন সংযোগ',
    mai: 'नब जडान',
    ks: 'نۆ کنکشن',
    sd: 'نئون ڪنيڪشن',
    kok: 'नवो जोडणी',
    mni: 'অনৌবা কন্নেক্সন',
    ne: 'नयाँ जडान',
    brx: 'गोदान फोनांजाब',
    doi: 'नमां कनेक्शन',
    sa: 'नूतन-सम्बन्धः',
    sat: 'ᱱᱟᱣᱟ ᱡᱚᱲᱟᱣ',
  },
  register_complaint: {
    en: 'Register Complaint',
    hi: 'शिकायत दर्ज करें',
    bn: 'অভিযোগ দায়ের',
    te: 'ఫిర్యాదు నమోదు',
    mr: 'तक्रार नोंदवा',
    ta: 'புகார் பதிவு',
    ur: 'شکایت درج کریں',
    gu: 'ફરિયાદ નોંધાવો',
    kn: 'ದೂರು ಸಲ್ಲಿಸಿ',
    ml: 'പരാതി നൽകുക',
    or: 'ଅଭିଯୋଗ ପଞ୍ଜିକରଣ',
    pa: 'ਸ਼ਿਕಾಯਤ ਦਰਜ ਕਰੋ',
    as: 'অভিযোগ পঞ্জীয়ন',
    mai: 'शिकायत दर्ज करू',
    ks: 'شکایت درج کٔریو',
    sd: 'شڪايت داخل ڪريو',
    kok: 'तक्रार नोंद करा',
    mni: 'ৱাকৎ লৌজিনবা',
    ne: 'गुनासो दर्ता',
    brx: 'अजद होनाय',
    doi: 'शकायत दर्ज करो',
    sa: 'परिवादं लिखतु',
    sat: 'ᱞᱟᱹᱞᱤᱥ ᱫᱚᱨᱡᱽ',
  },
  track_status: {
    en: 'Track My Request',
    hi: 'स्थिति ट्रैक करें',
    bn: 'অবস্থা ট্র্যাক',
    te: 'స్థితి ట్రాక్',
    mr: 'स्थिती तपासा',
    ta: 'நிலையை கண்காணியுங்கள்',
    ur: 'اسٹیٹس چیک کریں',
    gu: 'સ્થિતિ તપાસો',
    kn: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    ml: 'നില പരിശോധിക്കുക',
    or: 'ସ୍ଥିତି ଯାଞ୍ច',
    pa: 'ਸਥਿਤੀ ਦੀ ਜਾਂਚ',
    as: 'স্থিতি নিৰীক্ষণ',
    mai: 'स्थिति देखू',
    ks: 'حالت ژھانڈیو',
    sd: 'حالت چيڪ ڪريو',
    kok: 'स्थिती तपासात',
    mni: 'ফীভম চেক তৌবা',
    ne: 'स्थिति हेर्नुहोस्',
    brx: 'थाथाइ नायनाय',
    doi: 'हालत देखो',
    sa: 'स्थितिं पश्यतु',
    sat: 'ᱥᱛᱷᱤᱛᱤ ᱧᱮᱞ',
  },
  start: {
    en: 'Start',
    hi: 'शुरू करें',
    bn: 'শুরু করুন',
    te: 'ప్రారంభించండి',
    mr: 'सुरू करा',
    ta: 'தொடங்கு',
    ur: 'شروع کریں',
    gu: 'શરૂ કરો',
    kn: 'ಪ್ರಾರಂಭಿಸಿ',
    ml: 'തുടങ്ങുക',
    or: 'ଆରମ୍ଭ କରନ୍ତୁ',
    pa: 'ਸ਼ੁਰੂ ਕਰੋ',
    as: 'আৰম্ভ কৰক',
    mai: 'शुरू करू',
    ks: 'شۆروٗع کٔرِو',
    sd: 'شروع ڪريو',
    kok: 'सुरू करा',
    mni: 'হৌদোকপা',
    ne: 'सुरु गर्नुहोस्',
    brx: 'जागाय',
    doi: 'शुरू करो',
    sa: 'प्रारभत',
    sat: 'ᱮᱛᱚᱦᱚᱵ',
  },
  logout: {
    en: 'Logout',
    hi: 'लॉगआउट',
    te: 'లాగౌట్',
    ta: 'வெளியேறு',
    bn: 'লগআউট',
    mr: 'लॉगआउट',
  },
  dashboard: {
    en: 'Home',
    hi: 'होम',
    te: 'హోమ్',
    ta: 'முகப்பு',
    bn: 'হোম',
    mr: 'मुख्यपृष्ठ',
  },
  success: {
    en: 'Success!',
    hi: 'सफल!',
    te: 'విజయం!',
    ta: 'வெற்றி!',
    bn: 'সফল!',
    mr: 'यशस्वी!',
  },
  loading: {
    en: 'Wait',
    hi: 'प्रतीक्षा',
    te: 'వేచివుండండి',
    ta: 'காத்திருக்கவும்',
    bn: 'অপেক্ষা করুন',
    mr: 'प्रतीक्षा',
  },
  touch_to_start: {
    en: 'Tap',
    hi: 'टैप करें',
    te: 'ట్యాప్ చేయండి',
    ta: 'தட்டவும்',
    bn: 'ট্যাপ করুন',
    mr: 'टॅप करा',
  },
  gate_way_title: {
    en: 'Gateway',
    hi: 'गेटवे',
    te: 'గేట్‌వే',
    ta: 'நுழைவாயில்',
    bn: 'গেটওয়ে',
    mr: 'गेटवे',
  },
  smart_city_services: {
    en: 'City Services',
    hi: 'शहर सेवाएं',
    te: 'నగరం సేవలు',
    ta: 'நகர சேவைகள்',
    bn: 'নগর সেবা',
    mr: 'शहर सेवा',
  },
  footer_belongings: {
    en: 'Take items',
    hi: 'सामान लें',
    te: 'వస్తువులు తీసుకోండి',
    ta: 'பொருட்களை எடு',
    bn: 'জিনিস নিন',
    mr: 'सामान घ्या',
  },
  assisted_help: {
    en: 'Help',
    hi: 'मदद',
    te: 'సహాయం',
    ta: 'உதவி',
    bn: 'সাহায্য',
    mr: 'मदत',
  },
  citizen_services: {
    en: 'Services',
    hi: 'सेवाएं',
    te: 'సేవలు',
    ta: 'சேவைகள்',
    bn: 'সেবা',
    mr: 'सेवा',
  },
  mobile_no: {
    en: 'Mobile No.',
    hi: 'मोबाइल नं.',
    te: 'మొబైల్ నం.',
    ta: 'மொபைல் எண்',
    bn: 'মোবাইল নং',
    mr: 'मोबाईल क्र.',
  },
  consumer_no: {
    en: 'Cust No.',
    hi: 'उपभोक्ता नं.',
    te: 'వినియోగదారు నం.',
    ta: 'பயனர் எண்',
    bn: 'গ্রাহক নং',
    mr: 'ग्राहक क्र.',
  },
  get_otp: {
    en: 'Get OTP',
    hi: 'OTP लें',
    te: 'OTP పొందండి',
    ta: 'OTP பெறுக',
    bn: 'OTP পান',
    mr: 'OTP मिळवा',
  },
  verify: {
    en: 'Verify',
    hi: 'सत्यापित',
    te: 'ధృవీకరించండి',
    ta: 'சரிபார்',
    bn: 'যাচাই',
    mr: 'तपासा',
  },
  tracking_id: {
    en: 'Track ID',
    hi: 'ट्रैक ID',
    te: 'ట్రాక్ ID',
    ta: 'டிராக் ID',
    bn: 'ট্র্যাক ID',
    mr: 'ट्रॅक ID',
  },
  status: {
    en: 'Status',
    hi: 'स्थिति',
    te: 'స్థితి',
    ta: 'நிலை',
    bn: 'অবস্থা',
    mr: 'स्थिती',
  },
  error_otp: {
    en: 'Invalid OTP',
    hi: 'गलत OTP',
    te: 'తప్పు OTP',
    ta: 'தவறான OTP',
    bn: 'ভুল OTP',
    mr: 'चुकीचा OTP',
  },
  detected_region: {
    en: 'Loc.',
    hi: 'स्थान',
    te: 'స్థానం',
    ta: 'இடம்',
    bn: 'स्थान',
    mr: 'स्थान',
  },
  kill_kiosk: {
    en: 'Exit',
    hi: 'बाहर',
    te: 'నిష్క్రమించు',
    ta: 'வெளியேறு',
    bn: 'বাহির',
    mr: 'बाहेर',
  },
  tap_to_enter: {
    en: 'Tap',
    hi: 'टैप करें',
    te: 'నొక్కండి',
    ta: 'தட்டவும்',
    bn: 'ট্যাপ',
    mr: 'टॅप करा',
  },
  submit: {
    en: 'Submit',
    hi: 'जमा',
    te: 'సమర్పించు',
    ta: 'சமர்ப்பி',
    bn: 'জমা',
    mr: 'सबमिट करा',
  },
  verification_required: {
    en: 'Verify',
    hi: 'सत्यापन',
    te: 'ధృవీకరణ',
    ta: 'சரிபார்ப்பு',
    bn: 'যাচাই',
    mr: 'पडताळणी',
  },
  use_test_code: {
    en: '(Code 000)',
    hi: '(कोड 000)',
    te: '(కోడ్ 000)',
    ta: '(குறியீடு 000)',
    bn: '(কোড 000)',
    mr: '(कोड 000)',
  },
  change_number: {
    en: 'Change No.',
    hi: 'नंबर बदलें',
    te: 'నంబర్ మార్చండి',
    ta: 'எண் மாற்று',
    bn: 'নম্বর পরিবর্তন',
    mr: 'नंबर बदला',
  },
  touch_input: {
    en: 'Type',
    hi: 'टाइप करें',
    te: 'టైప్ చేయండి',
    ta: 'தட்டச்சு செய்',
    bn: 'টাইপ করুন',
    mr: 'टाईप करा',
  },
  electricity: {
    en: 'Power',
    hi: 'बिजली',
    te: 'విద్యుత్',
    ta: 'மின்சாரம்',
    bn: 'বিদ্যুৎ',
    mr: 'वीज',
  },
  water: {
    en: 'Water',
    hi: 'पानी',
    te: 'నీరు',
    ta: 'நீர்',
    bn: 'জল',
    mr: 'पाणी',
  },
  gas: {
    en: 'Gas',
    hi: 'गैस',
    te: 'గ్యాస్',
    ta: 'எரிவாயு',
    bn: 'গ্যাস',
    mr: 'गॅस',
  },
  domestic: {
    en: 'Home',
    hi: 'घरेलू',
    te: 'గృహ',
    ta: 'வீடு',
    bn: 'বাড়ি',
    mr: 'घरगुती',
  },
  commercial: {
    en: 'Shop',
    hi: 'दुकान',
    te: 'దుకాణం',
    ta: 'கடை',
    bn: 'দোকান',
    mr: 'व्यावसायिक',
  },
  industrial: {
    en: 'Factory',
    hi: 'फैक्ट्री',
    te: 'ఫ్యాక్టరీ',
    ta: 'தொழிற்சாலை',
    bn: 'कारখানা',
    mr: 'औद्योगिक',
  },
  personal_details: {
    en: 'Details',
    hi: 'विवरण',
    te: 'వివరాలు',
    ta: 'விவரங்கள்',
    bn: 'বিবরণ',
    mr: 'तपशील',
  },
  applicant_name: {
    en: 'Name',
    hi: 'नाम',
    te: 'పేరు',
    ta: 'பெயர்',
    bn: 'নাম',
    mr: 'नाव',
  },
  identity_proof: {
    en: 'ID No.',
    hi: 'ID नं.',
    te: 'ID నం.',
    ta: 'ID எண்',
    bn: 'আইডি নং',
    mr: 'ID क्र.',
  },
  choose_service_desc: {
    en: 'Select',
    hi: 'चुनें',
    te: 'ఎంచుకోండి',
    ta: 'தேர்வு',
    bn: 'বাছুন',
    mr: 'निवडा',
  },
  choose_category_desc: {
    en: 'Select',
    hi: 'चुनें',
    te: 'ఎంచుకోండి',
    ta: 'தேர்வு',
    bn: 'বাছুন',
    mr: 'निवडा',
  },
  select_service: {
    en: 'Service',
    hi: 'सेवा',
    te: 'సేవ',
    ta: 'சேவை',
    bn: 'সেবা',
    mr: 'सेवा',
  },
  select_category: {
    en: 'Category',
    hi: 'श्रेणी',
    te: 'వర్గం',
    ta: 'வகை',
    bn: 'বিভাগ',
    mr: 'श्रेणी',
  },
  check_usage: {
    en: 'Usage',
    hi: 'उपयोग',
    te: 'వాడుక',
    ta: 'பயன்பாடு',
    bn: 'ব্যবহার',
    mr: 'वापर',
  },
  reprint_receipts: {
    en: 'Receipts',
    hi: 'रसीदें',
    te: 'రసీదులు',
    ta: 'ரசீதுகள்',
    bn: 'রসিদ',
    mr: 'पावत्या',
  },
  done: {
    en: 'Done',
    hi: 'पूर्ण',
    te: 'పూర్తయింది',
    ta: 'முடிந்தது',
    bn: 'সম্পন্ন',
    mr: 'पूर्ण',
  },
  cancel: {
    en: 'Cancel',
    hi: 'रद्द',
    te: 'రద్దు',
    ta: 'ரத்து',
    bn: 'বাতিল',
    mr: 'रद्द',
  },
  type_here: {
    en: 'Type...',
    hi: 'यहाँ लिखें...',
    te: 'ఇక్కడ టైప్...',
    ta: 'இங்கே தட்டச்சு...',
    bn: 'এখানে টাইপ...',
    mr: 'येथे लिहा...',
  },
  assisted_cash: {
    en: 'Cash',
    hi: 'नकद',
    te: 'నగదు',
    ta: 'பணம்',
    bn: 'নগদ',
    mr: 'रोख',
  },
  bank_payment: {
    en: 'Bank',
    hi: 'बैंक',
    te: 'బ్యాంకు',
    ta: 'வங்கி',
    bn: 'ব্যাংক',
    mr: 'बँक',
  },
  bill_summary: {
    en: 'Summary',
    hi: 'सारांश',
    te: 'సారాంశం',
    ta: 'சுருக்கம்',
    bn: 'সারসংক্ষেপ',
    mr: 'सारांश',
  },
  credit_card: {
    en: 'Credit',
    hi: 'क्रेडिट',
    te: 'క్రెడిట్',
    ta: 'கிரெடிட்',
    bn: 'ক্রেডিট',
    mr: 'क्रेडिट',
  },
  debit_card: {
    en: 'Debit',
    hi: 'डेबिट',
    te: 'డెబిట్',
    ta: 'டெபிட்',
    bn: 'ডেবিট',
    mr: 'डेबिट',
  },
  select_bank: {
    en: 'Bank',
    hi: 'बैंक',
    te: 'బ్యాంకు',
    ta: 'வங்கி',
    bn: 'ব্যাংক',
    mr: 'बँक',
  },
  upi: {
    en: 'UPI',
    hi: 'UPI',
    te: 'UPI',
    ta: 'UPI',
    bn: 'UPI',
    mr: 'UPI',
  },
  print: {
    en: 'Print',
    hi: 'प्रिंट',
    te: 'ప్రింట్',
    ta: 'அச்சிடு',
    bn: 'প্রিন্ট',
    mr: 'प्रिंट',
  },
  fetch_bill: {
    en: 'Fetch',
    hi: 'खोजें',
    te: 'వెతకండి',
    ta: 'தேடு',
    bn: 'খোঁজা',
    mr: 'शोधा',
  },
  complaint_type: {
    en: 'Type',
    hi: 'प्रकार',
    te: 'రకం',
    ta: 'வகை',
    bn: 'প্রকার',
    mr: 'प्रकार',
  },
  description: {
    en: 'Desc',
    hi: 'विवरण',
    te: 'వివరణ',
    ta: 'விளக்கம்',
    bn: 'বিবরণ',
    mr: 'वर्णन',
  },
  grievance_form: {
    en: 'Form',
    hi: 'फॉर्म',
    te: 'ఫారం',
    ta: 'படிவம்',
    bn: 'ফর্ম',
    mr: 'फॉर्म',
  },
  auto_logout_in: {
    en: 'Logout in',
    hi: 'लॉगआउट में',
    te: 'లాగౌట్ లో',
    ta: 'வெளியேறு',
    bn: 'লॉगআউট',
    mr: 'लॉगआउट',
  },
  no_sign_out: {
    en: 'Exit',
    hi: 'बाहर',
    te: 'నిష్క్రమించు',
    ta: 'வெளியேறு',
    bn: 'বাহির',
    mr: 'बाहेर',
  },
  session_expired: {
    en: 'Expired',
    hi: 'समाप्त',
    te: 'గడువు ముగిసింది',
    ta: 'முடிந்தது',
    bn: 'মেয়াদোত্তীর্ণ',
    mr: 'कालबाह्य',
  },
  session_timeout_msg: {
    en: 'Extend?',
    hi: 'बढ़ाएं?',
    te: 'పొడిగించాలా?',
    ta: 'நீட்டிக்கவா?',
    bn: 'বাড়াতে চান?',
    mr: 'वाढवायचे?',
  },
  yes_extend: {
    en: 'Yes',
    hi: 'हाँ',
    te: 'అవును',
    ta: 'ஆம்',
    bn: 'হ্যাঁ',
    mr: 'होय',
  },
  login_title: {
    en: 'Sign In',
    hi: 'साइन इन करें',
    bn: 'সাইন ইন',
    te: 'సైన్ ఇన్',
    mr: 'साइन इन करा',
    ta: 'உள்நுழைய',
    ur: 'سائن ان کریں',
    gu: 'સાઇન ઇન કરો',
    kn: 'ಸೈನ್ ಇನ್',
    ml: 'സൈൻ ഇൻ ചെയ്യുക',
    or: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    pa: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    as: 'ছাইন ইন',
    mai: 'साइन इन करू',
    ks: 'سائن اِن',
    sd: 'سائن ان ڪريو',
    kok: 'साइन इन करात',
    mni: 'সাইন ইন তৌবিয়ু',
    ne: 'साइन इन गर्नुहोस्',
    brx: 'साइन इन खालाम',
    doi: 'साइन इन करो',
    sa: 'प्रविशतु',
    sat: 'ᱥᱟᱭᱤᱱ ᱤᱱ ᱢᱮ',
  },
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {};

// Initialize TRANSLATIONS object for all supported languages
SUPPORTED_LANGUAGES.forEach((lang) => {
  TRANSLATIONS[lang.id] = {};

  // Overlay core keys
  Object.keys(CORE_KEYS).forEach((key) => {
    const translations = CORE_KEYS[key as keyof typeof CORE_KEYS];
    if (translations[lang.id as keyof typeof translations]) {
      TRANSLATIONS[lang.id][key] = translations[lang.id as keyof typeof translations]!;
    }
  });
});

export const getTranslation = (id: string, key: string) => {
  return TRANSLATIONS[id]?.[key] || TRANSLATIONS['en']?.[key] || key;
};
